# Generated by Django 4.2.1 on 2023-06-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=200, verbose_name='إسم القسم | Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='summary',
            field=models.CharField(max_length=1000, verbose_name='نبذه مختصره عن القسم | Description From Category '),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category', verbose_name='إسم القسم | Category Name'),
        ),
    ]
